# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3771fdbc96f8319c3a8592c7b161f624528760b1a8f70d06acf6bd69f56f097bf0b86fdc7a1f2f548bdafc395d3f949ce4c960ed904e347c2bee54cf95a8874f

test:
  secret_key_base: 719c81733bbd8979a4496243bd99351d430009434a794a1adf5c5e2fcd471697145f692c3a75d42a436ac678ec792d5083a89298c8112e9bd81f7207c0141fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
